[MVC - Step 1] 올라프 미션 제출합니다.
woowacourse/jwp-mvc pull request #11
Opened 2019-10-02 08:32 UTC by school0bhy

안녕하세요 홍시, 리뷰이 올라프입니다!

많은 지적 부탁드립니다 :)

2019-10-03 02:44 UTC, hongsii requested changes
안녕하세요, 올라프!
전반적으로 구현을 잘 해주셔서 피드백 드릴게 없네요 👍 
간단한 피드백을 드렸으니, 반영해보시면 좋을 것 같아요 :)

2019-10-03 02:44 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                .collect(Collectors.toSet());
[Reflections(Object... params)](https://static.javadoc.io/org.reflections/reflections/0.9.10/org/reflections/Reflections.html#Reflections-java.lang.Object...-) 를 활용하면 패키지마다 `Reflections` 인스턴스를 만들 필요가 없습니다.

2019-10-03 02:44 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +    String execute(HttpServletRequest req, HttpServletResponse resp) throws Exception;
요구사항1에 따르면 아래와 같은 메서드를 사용자가 만들 수 있습니다. `String` 뿐만 아니라 여러 타입도 지원하도록 바꿔보면 어떨까요?

``` java
    @RequestMapping("/users")
    public ModelAndView list(HttpServletRequest request, HttpServletResponse response) {
        logger.debug("users findUserId");
        return new ModelAndView(new JspView("/users/list.jsp"));
    }
```

2019-10-04 04:49 UTC, school0bhy commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                .collect(Collectors.toSet());
제가 잘못 사용하고 있었네요.. 짚어주셔서 감사합니다ㅎㅎ

2019-10-05 14:36 UTC, school0bhy commented
안녕하세요 홍시! 피드백 반영이 오래 걸린것 같아 죄송합니다ㅠㅠ
기존의 구현방식이 레거시 코드에 많은 수정이 있었던 것 같아 다시 한번 구현해보았습니다.
남겨주신 피드백 또한 반영했습니다ㅎㅎ
많은 지적 부탁드립니다. 감사합니다!

2019-10-05 14:56 UTC, hongsii approved these changes
구현을 깔끔하게 해주셔서 피드백 드릴게 없네요 💯 
간단한 피드백 한 가지 드렸으니, 다음 단계에서 같이 반영해보세요 :)

2019-10-05 14:56 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        view.render(modelAndView.getModel(), req, resp);
`ModelAndView` 로 메시지를 보내 처리하면 getter를 제거할 수 있을 듯 합니다.

2019-10-05 14:56 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/handleradapter/HandlerAdapter.java
> +public interface HandlerAdapter {
추상화 👍

2019-10-05 14:57 UTC, merged