[MVC - Step 1] 희봉 미션 제출합니다.
woowacourse/jwp-mvc pull request #17
Opened 2019-10-02 09:01 UTC by heebong

안녕하세요, Summer님! 이번 리뷰를 받게된 희봉입니다.
가까스로 요구사항만 맞추며 개발해 ```if-else```와 ```instanceof```를 자주 사용했습니다... 😭 
현재 ```HandlerExecution``` 의 ```handle()```에서 뷰를 만들어주는데, 뷰가 늘어남에 따라 ```handle()```의 길이가 같이 길어지는 구조입니다.
때문에 더 좋은 방법이 있을 지 알고싶습니다ㅠㅠ

피드백 많이 부탁드립니다! 미리 감사드립니다!

2019-10-04 04:36 UTC, gracefulBrown requested changes
안녕하세요. (잠시)리뷰를 맡은 브라운입니다.
전반적으로 깔끔하게 기능구현 잘 해주셨네요 👍 
몇가지 코멘트 남기니 확인해보시고 미션진행해주세요~
궁금한 점 있으시면 언제든 DM보내주세요 :)

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        if (requestMapping.getHandler(request) != null) {
mapping 방법이 늘어날수록 requestMapping나 annotationHandlerMapping와 같은 필드가 늘어날 것 같고 if문 또한 케이스가 늘어날 것 같은데요~ 조금 더 유연한 방법으로 handler를 찾을 수 있게 리팩토링해보면 어떨까요?

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                throw new Exception();
예외 발생 시 처리를 조금 더 명확하게 해주면 좋을 것 같아요 :0

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            if (((String) view).startsWith(DEFAULT_REDIRECT_PREFIX)) {
DispatcherServlet에서도 위와같이 DEFAULT_REDIRECT_PREFIX임을 확인하는 로직이 있는 것 같은데 
분기처리하는 부분을 둘 중 하나는 제거할 수 있지 않을까요?

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
Handler를 Mapping하는 역할을 가진 클래스에서 대상이 되는 `Controller 클래스를 스캔하는 부분`을 분리해보면 어떨까요?

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/MyController.java
>      private static final Logger logger = LoggerFactory.getLogger(MyController.class);
프레임워크의 실제 테스트 클래스 이외에 학습에 필요한 테스트 클래스를 별도의 패키지로 관리하면 어떨까요?

2019-10-04 04:36 UTC, gracefulBrown commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>  public class AnnotationHandlerMappingTest {
꼼꼼한 테스트 👍

2019-10-07 07:52 UTC, heebong commented
안녕하세요~ 피드백 감사드립니다!!
최대한 반영을 하려고 노력했습니다만...쉽지않네요ㅠㅠ
이번 피드백에선 ```Handler``` 인터페이스를 추가해서 ```Controller```와 ```HandlerExecution```이 상속받게 변경했습니다.
또한 ```ViewAdapter```를 만들어서 ```handler.handle(req,resp)```의 값을 받아서 ```ModelAndView```로 바꾸는 작업을 추가했습니다.

여기서 궁금한점이, ```handler.handle(req,resp)``` 의 리턴타입은 ```Object```인데 그걸 받아서 처리하는 객체 이름이 ```ViewAdapter```여도 될지입니다. 그렇다고 ```handler.handle(req,resp)```의 리턴타입을 ```View```로 한정짓기엔 리턴타입을 바로 ```ModelAndView```로 설정할 수도 있어서... 한번 더 나눠야할지, 나눈다면 어떻게 나눠야할지 고민입니다.

피드백 반영을 늦게해서 죄송합니다ㅠ 다음 피드백 미리 감사드립니다!!

2019-10-07 07:53 UTC, heebong commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        if (requestMapping.getHandler(request) != null) {
```Handler``` 객체를 만들어서 리턴타입을 ```Object```가 아닌 ```Handler```로 변경했습니다!

2019-10-07 07:53 UTC, heebong commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                throw new Exception();
```NotMatchHandlerException```을 만들었습니다. 확인 부탁드립니다!

2019-10-07 07:54 UTC, heebong commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            if (((String) view).startsWith(DEFAULT_REDIRECT_PREFIX)) {
```Object```를 ```ModelAndView```로 바꿔주는 작업을 하는 ```ViewAdapter```를 생성해 그것을 사용하도록 변경했습니다. 확인 부탁드립니다!

2019-10-07 07:56 UTC, heebong commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
```basePackage```를 받아 ```Controller```를 스캔하는 객체를 생성했습니다. 확인 부탁드립니다!

2019-10-07 07:56 UTC, heebong commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/MyController.java
>      private static final Logger logger = LoggerFactory.getLogger(MyController.class);
따로 분리했습니다. 확인 부탁드립니다!

2019-10-07 07:56 UTC, heebong commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>  public class AnnotationHandlerMappingTest {
감사합니당!

2019-10-07 09:46 UTC, gracefulBrown requested changes
피드백 반영 잘 해주셨습니다 :)
오프라인으로 잠깐 이야기 나눈 부분에 대해서 고민해보시면 좋을 것 같아요!

2019-10-07 09:46 UTC, gracefulBrown commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            ModelAndView modelAndView = ViewAdapter.render(view);
오프라인에서 이야기 나눈것과 같이
DispatcherServlet에서 ModelAndView를 결정하는 것 보다 
handle의 결과로 ModelAndView를 받아서 처리하도록 하는 건 어떨까요?

2019-10-07 09:52 UTC, heebong commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            ModelAndView modelAndView = ViewAdapter.render(view);
handler의 리턴타입을 ModelAndView로 변경했습니다. 확인 부탁드립니다!

2019-10-10 01:46 UTC, gracefulBrown approved these changes
피드백 반영 잘 해주셨네요 👍 
머지하겠습니다~

2019-10-10 01:46 UTC, merged