[MVC - Step 1] 아이크 미션 제출합니다.
woowacourse/jwp-mvc pull request #19
Opened 2019-10-02 12:25 UTC by ike5923

안녕하세요. 이번에 처음 리뷰를 받게된 아이크입니다!
이번 1단계 미션에서는 mvc에 대한 깊은 이해보다는 리플렉션과 레거시 코드에 새로운 코드를 접하면서 생기는 리펙토링이 주가 되었던 것 같습니다.
리펙토링 관련해서 아직 미흡하지만 피드백 반영하면서 수정해보고자합니다.
많은 피드백 부탁드립니다!!!

2019-10-03 16:51 UTC, kingbbode requested changes
안녕하세요 아이크!
잘 구현해주셨어요 👍 
다음 단계를 위해 미리 확인하였으면 하는 부분이 있어코멘트 남겼어요! 
확인 부탁드려요 :)

2019-10-03 16:51 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        HandlerMapping annotationHandlerMapping = handlerMappings.get(1);
handlerMappings 의 구현체가 늘어도 코드의 변경없이 처리될 수 있도록 추상화되었으면 좋겠어요!
Handler 와 View 가 확장되어도 분기문이 늘지 않을 수 있도록 Handler 와 View 에 대한 처리를 각각 추상화해보는 것은 어떨까요?

```
Object view = requestHandler.execute(req, resp);
viewResolver.resolve(view)
```
(예시코드일뿐 실제 위와 같이 하지 않아도 됩니다.)

2019-10-03 16:51 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +    public nextstep.mvc.asis.Controller getHandler(String requestUri) {
의미 있는 구현체일까요?

2019-10-03 16:51 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            return (ModelAndView) method.invoke(method.getDeclaringClass().getConstructor().newInstance(), request, response);
인스턴스가 항상 생성되어야할까요?

2019-10-03 16:51 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            logger.error(e.getMessage());
메시지 이외의 예외 정보가 유실되어 추적이 쉽지 않겠네요. HandlerExecution이 예외를 삼켜버리기보다는 다른 레이어에 전달할 수 있으면 일관된 예외처리와 추적을 하기에 용이하지 않을까요?

2019-10-03 16:51 UTC, kingbbode commented on study/src/test/java/reflection/ReflectionTest.java
> +        }
확인이 가능한 테스트는 assert 로 작성하셨으면 좋겠네요 :)

2019-10-04 00:49 UTC, ike5923 commented on study/src/test/java/reflection/ReflectionTest.java
> +        }
구현한 다른 테스트에 대해서도 적용할 수 있는 부분을 찾아봤지만, 아직 없는 것 같아서 이 부분만 적용했습니다.

2019-10-04 03:28 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            return (ModelAndView) method.invoke(method.getDeclaringClass().getConstructor().newInstance(), request, response);
HandlerExcution 객체가 생성되는 시점에 reflection된 mehtod와 함께 인스턴스로 관리하도록 변경했습니다.

2019-10-04 06:11 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +            logger.error(e.getMessage());
말씀하신대로 `handle` method 내부에서 예외를 잡기보다는 `DispatcherServlet`에서 잡는 것이 맞다고 생각했습니다. 그래서 해당 예외를 상위 레이어로 올려서 처리하도록 변경했습니다.

2019-10-04 06:22 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +    public nextstep.mvc.asis.Controller getHandler(String requestUri) {
의미 없는 구현체를 제거하기 위해 `HandlerMapping`의 `getHandler()`를 수정했습니다.

2019-10-07 07:48 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        HandlerMapping annotationHandlerMapping = handlerMappings.get(1);
처음에 dispatcher에서 slipp모듈을 접근하려다가 발생하는 에러에 대해서 파악을 못해서 삽질을 오래 했네요...ㅜㅜ 그래서 `viewResolver`를 `SlippWebApplicationInitializer`에서 생성해서 Dispatcher에 주입하는 방식으로 변경했습니다. map을 이용해서 viewResolver를 담아서 주는 방식에 대해서는 어떻게 생각하시는지 궁금합니다!

2019-10-07 11:06 UTC, kingbbode approved these changes
피드백 반영 잘 반영해주셨네요 👍 
추가 구현에 대한 코멘트 작성하였습니다!
다음 단계 진행 전에 고려해보시면 좋을 것 같아요 :)

2019-10-07 11:06 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/asis/Controller.java
> +public interface Controller extends HandlerResolver {
기존 코드에 새로운 사용성을 불어넣는 것이 사용성에 대한 혼란을 가중시키지 않을까요?
기존 코드와 사용성을 변경하지 않고 해결하는 방식을 고민해보아도 좋을 것 같습니다.

2019-10-07 11:06 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        handlerExecutions.put(new HandlerKey(requestMapping.value(), requestMapping.method()), new HandlerExecution(method, clazz, viewResolvers.get(method.getReturnType())));
현재는 문제없겠으나 반환 타입만으로 반환될 데이터의 형태를 결정짓는 것은 섣부르지 않을까요? :)
Object 타입으로 선언되어 있을 때 View 를 결정해놓을 수 있을까요?

2019-10-07 11:07 UTC, merged

2019-10-09 09:30 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/asis/Controller.java
> +public interface Controller extends HandlerResolver {
adapter를 적용해서 기존 legacy코드에 사용성을 추가하지 않도록 변경했습니다!

2019-10-09 15:24 UTC, ike5923 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        handlerExecutions.put(new HandlerKey(requestMapping.value(), requestMapping.method()), new HandlerExecution(method, clazz, viewResolvers.get(method.getReturnType())));
viewResolver를 dispatcherServlet에서 결정하도록 변경했습니다. view name을 통해 지원하는 view를 찾아서 적용할 수 있도록 했습니다.