[MVC - Step 1] 버디 미션 제출합니다.
woowacourse/jwp-mvc pull request #23
Opened 2019-10-03 09:28 UTC by imkimheejoo

안녕하세요 브리님 이번 mvc 리뷰이 버디입니다!
많은 피드백 부탁드립니다!

2019-10-04 04:01 UTC, byjo requested changes
버디 안녕하세요. 이번 미션 리뷰를 맡은 브리입니다.
학습 테스트 및 미션 구현 잘 하셨네요. 👍 
몇 가지 개선하면 좋을 점이 보여 피드백 드렸으니 확인해주세요.
새로 만든 어노테이션을 사용한 Controller나 DispatcherServlet에 대한 테스트를 추가하고 리팩토링을 진행해보시면 더 좋을 것 같아요. 😊
혹시나 궁금한 점 있다면 편하게 문의 주세요. 개선된 코드 기대해보겠습니다!

2019-10-04 04:01 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMapping manualHandlerMapping, AnnotationHandlerMapping annotationHandlerMapping) {
파라미터 타입으로 구현체보다는 인터페이스를 쓰는 것이 좋지 않을까요?

2019-10-04 04:01 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            Object handler = manualHandlerMapping.getHandler(req);
새로운 매핑이 추가된다면 elseif 문이 추가되어야 하는 걸까요? OCP에 어긋나는 것 같습니다.
다음 부분을 추상화 하여 if-else 분기를 제거해보면 좋을 것 같아요.
1. Handler를 가져오는 로직
   이 로직은 HandlerMapping 인터페이스를 통해 이뤄질 수 있겠네요.
2. 가져온 Handler를 실행하는 로직

2019-10-04 04:01 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        for (Class<?> aClass : typesAnnotatedWith) {
이 메소드 안에서 Controller 스캔, Method 추출, Annotation 추출 등 타고 들어가는 로직이 많아 흐름 파악이 어렵네요.
`initialize()` 내 로직을 좀 더 가독성 좋게 분리하면 좋을 것 같아요.

- [객체지향 생활체조 규칙 1 - 메서드당 들여쓰기 한 번](https://developerfarm.wordpress.com/2012/01/26/object_calisthenics_2/)

2019-10-04 04:01 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                handlerExecutions.put(createHandlerKey(rm),
아래 요구사항을 만족하고 있을까요?
> @RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.

2019-10-04 04:01 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(new HandlerKey(url, requestMethod));
현재 HandlerKey의 requestMethods 필드 타입이 배열인데요.
```
RequestMethod[] requestMethod = {RequestMethod.valueOf(request.getMethod())};
```
위 코드를 통해 만들어진 requestMethod는 항상 length가 1인 배열이겠죠.
HandlerExecution이 여러 메소드를 지원하는 경우, 이에 맞는 handlerExecution을 가져올 수 있을까요?

2019-10-04 04:11 UTC, imkimheejoo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMapping manualHandlerMapping, AnnotationHandlerMapping annotationHandlerMapping) {
수정했습니다~

2019-10-06 11:12 UTC, imkimheejoo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            Object handler = manualHandlerMapping.getHandler(req);
수정했습니다!

2019-10-06 12:08 UTC, imkimheejoo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        for (Class<?> aClass : typesAnnotatedWith) {
수정했습니다!

2019-10-06 12:58 UTC, imkimheejoo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(new HandlerKey(url, requestMethod));
수정했습니다!

2019-10-06 12:59 UTC, imkimheejoo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                handlerExecutions.put(createHandlerKey(rm),
RequestMethod에 ALL을 추가하여 method 설정이 없을 시 All을 설정하게 수정하였습니다!

2019-10-07 12:03 UTC, byjo approved these changes
피드백드린 누락된 요구사항 충족과 리팩토링 잘 진행 하셨네요. 👍
다만 Mapping이 추가되면서 프레임워크가 해야할 역할을 어플리케이션에서 직접 구현해야 하는 이슈가 있어 보입니다.
코멘트 드린 부분 참고하셔서 2단계 미션을 하면서 함께 반영 부탁드려요. 😊
혹시나 진행하시면서 궁금하거나 이야기 나눠보고 싶은 부분 있다면 편하게 문의 주시구요!

2019-10-07 12:03 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerScan.java
> +class ControllerScan {
클래스명은 명사형이 좋을 것 같아요.

2019-10-07 12:03 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                .filter(hk -> hk.containsMethodType(requestMethod))
stream filter를 두 번 타야하는데, 이를 줄여보면 어떨까요?

2019-10-07 12:03 UTC, byjo commented on slipp/src/main/java/slipp/ManualHandlerMappingAdapter.java
> +public class ManualHandlerMappingAdapter implements HandlerMapping {
Adapter를 프레임워크가 아닌 어플리케이션에서 정의하고 설정하고 있네요. 
https://github.com/woowacourse/jwp-mvc/blob/7bfdcb391eac838785cd769d74b32c2f6785cd05/slipp/src/main/java/slipp/SlippWebApplicationInitializer.java#L18
그렇다면 구현하신 프레임워크를 사용하는 어플리케이션마다 ManualHandlerMappingAdapter 코드를 작성해야 하는 걸까요? 
만약 다른 프레임워크나 라이브러리를 사용한 Controller를 등록하고 싶은 경우, 이에 맞는 Adapter 또한 어플리케이션 개발자가 구현해야 하는 사항일까요?
위와 같다면 프레임워크의 사용성이 낮은 것 같습니다.

어플리케이션에서는 정해진 규칙에 맞는 Mapping을 구현하고, 
프레임워크는 Mapping 구현체에 따라 적합한 Adapter를 사용해 요청을 처리하면 어떨까요?

2019-10-07 12:03 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                .filter(handlerMapping -> Objects.nonNull(handlerMapping.getHandler(req)))
stream API 사용 시, 함수형 프로그래밍의 패러다임에 맞게 사용하는 것이 중요할 것 같아요.
값을 구하는 부분과 필터링 하는 부분을 분리하면 어떨까요? 
그리고 handler를 가져오는 부분도 별도의 메소드로 분리되면, `service()` 메소드 내 로직 가독성이 더 좋아질 것 같아요.

2019-10-07 12:03 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMapping manualHandlerMapping, AnnotationHandlerMapping annotationHandlerMapping) {
Mapping의 개수나 타입에 제한을 두지 않으면 어플리케이션에서 더 편하고 확장성 있게 프레임워크를 사용할 수 있지 않을까요?
```suggestion
    public DispatcherServlet(List<HandlerMapping> handlerMappings) {
```
혹은 
```suggestion
    public DispatcherServlet(HandlerMapping... handlerMappings) {
```

2019-10-07 12:03 UTC, merged