[MVC - Step 1] 효오 미션 제출합니다.
woowacourse/jwp-mvc pull request #28
Opened 2019-10-04 08:06 UTC by hyojaekim

안녕하세요! 효오 입니다.

아직 부족하지만 많은 지적 부탁드리겠습니다!

2019-10-04 20:09 UTC, woowahanCU requested changes
안녕하세요! 정훈님이 개인적인 사정이 있어서 대신 리뷰남겨요~ 😀
상당부분 잘 구현하셨는데요. 이번 미션 진행하면서 구현한 기능들에 대한 테스트코드를 작성하지 않아 아쉽네요. 
어렵더라도 작성해보는 연습을 해보시는게 좋을거 같아요. 
몇가지 피드백 남겨두었으니 확인해보시고 궁금한 점 있으면 Comment남기시면 포비가 답변주실거에요 😈

2019-10-04 20:09 UTC, woowahanCU commented on study/src/test/java/reflection/ReflectionTest.java
> +        }
미션이 출력을 하는 것들 이었지만, 값을 비교하는 테스트를 작성하는 것이 더 좋다고 생각합니다.
테스트 코드를 작성하는 것은 리팩토링하는 과정을 돕기도 하지만, 배포 파이프라인에서도 의미를 갖는다고 생각하는데요. 
단순히 출력하는 테스트는 리팩토링 과정에서는 사용자의 확인을 필요로하고, 배포 파이프라인에서는 별다른 의미를 갖지 않게 된다고 생각합니다.

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        addController("/users/logout", RequestMethod.GET);
Reflection을 적극적으로 사용하면 RequestMethod를 인자로 받는 부분을 없앨 수 있지 않을까요
그리고 현재는 addController 메서드에서 매번 ControllerScanner.scan 메서드를 호출하고 있네요.
아래와 같이 Controller별로 Annotation이 붙은 메서드만 찾는 것은 어떨까요

```java
            Method[] methods = Arrays.stream(controller.getDeclaredMethods())
                    .filter(it -> it.isAnnotationPresent(RequestMapping.class))
                    .toArray(Method[]::new);
```

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
>      public HandlerExecution getHandler(HttpServletRequest request) {
method 순서에 대해서 다시 한번 고민해보셔요.

https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JspView.java
> +    private static final String DEFAULT_REDIRECT_PREFIX = "redirect:";
JspView와  redirect는 별개로 보이는데요. redirect의 경우 dispatch도 필요없어 보이구요
RedirectView를 별도로 작성하는 것은 어떨까요

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/web/annotation/RequestMethod.java
> +    public static RequestMethod of(String requestMethod) {
enum의 valueOf 메서드를 활용해도 되지 않을까요

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        throw new IllegalArgumentException();
RequestMapping에 Method를 설정하지 않았을 시에는 요구사항에 있는 것처럼 해당 URL에 대해 모든 Method로 요청할 수 있습니다. 이 기능이 구현되지 않았네요. 
그리고 특정 Method로 설정해두었을 경우 그 외의 Method로 요청시에는 405 로 응답합니다.

https://tools.ietf.org/html/rfc7231#section-6.5.5

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/HandlerMapping.java
> +    Object getHandler(HttpServletRequest request);
HandlerExecution으로 리턴 받는다면 DispatcherServlet에서 if 분기 처리하는 상당부분, instaceof 등이 제거될 수 있겠어요

2019-10-04 20:09 UTC, woowahanCU commented on slipp/src/main/java/slipp/controller/tobe/UpdateLoginController.java
> +        }
아래의 코드와 중복이네요

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    private List<HandlerMapping> handlerMappings;
👍

2019-10-04 20:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
DispatcherServlet은 HandlerMapping 인터페이스의 getHandler 메서드의 리턴타입 변경 후 구조적으로 상당부분 개선이 될 것으로 보입니다.

2019-10-04 20:12 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        throw new IllegalArgumentException();
https://woowacourse.slack.com/archives/CFELTJH51/p1569992156039800

2019-10-05 10:12 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        addController("/users/logout", RequestMethod.GET);
다시 생각해보니 인자도 받을 필요가 없었고, 매번 ControllerScanner의 메소드를 호출할 필요도 없었네요! 좋은 피드백 감사합니다!

궁금한게 있습니다. 저는 Controller에서 Mapping(@GetMapping, @RequestMapping....) 관련 어노테이션이 붙은 메서드 접근 제어자를 public으로 두고,
로직을 분리할 때 분리한 메서드 접근 제어자를 대부분 private로 선언 했었습니다. 
그래서 굳이 접근 불가능한 메서드를 가져오지 않아도 괜찮다고 생각해서 getMethods를 사용했는데
피드백 주신 코드에서 getDeclaredMethods()를 사용한 이유가 있을까요?

2019-10-06 11:12 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/HandlerMapping.java
> +    Object getHandler(HttpServletRequest request);
리턴 타입을 HandlerExecution 으로 바꾸면서, 여러번 코드를 작성했다 지웠다를 반복했습니다.
리턴 타입만 바꿨는데 DispatcherServlet에서 분기 처리하는 부분이 없어지면서 코드가 깔끔해졌습니다!
좋은 피드백 감사합니다.

2019-10-06 11:15 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
리턴 타입을 HandlerExecution 으로 바꾸면서, 여러번 코드를 작성했다 지웠다를 반복했습니다.
이러한 과정을 겪으니 확실히 코드가 전보다 깔끔해지고, 이해도가 높아졌습니다.

리턴 타입만 바꿨는데 DispatcherServlet에서 분기 처리하는 부분이 없어져서 전보다 깔끔하네요!
좋은 피드백 감사합니다!

2019-10-07 07:49 UTC, hyojaekim commented
테스트 코드는 PR 보내고 추가하겠습니다!

2019-10-07 12:09 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        addController("/users/logout", RequestMethod.GET);
아니요. getMethods()를 사용하시면 됩니다 ㅎㅎ;

2019-10-07 12:37 UTC, woowahanCU approved these changes
피드백 반영 잘해주셨네요! 👍 
다음 단계 진행하시면 됩니다~  :)

2019-10-07 12:37 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                        .forEach(method -> putHandlerExecution(controller, method))
stream api의 foreach는 가급적 출력 용도로만 활용해주시기 바랍니다.
로직을 수행할 거면 반복문을 사용하시는게 객체지향적인 설계를 가능케 한다고 생각합니다.
foreach에서 로직이 수행될 경우 동시성 보장이 어려워지고 가독성이 떨어져 effective java item 46에서는 주의해서 사용하길 권하고 있습니다.

추가적으로, stream api는 지연연산을 하므로 일반적인 loop와 다르게 동작하므로 결과가 예측과 다를 수 있습니다.
https://www.popit.kr/java8-stream은-loop가-아니다/

2019-10-07 12:37 UTC, merged