[MVC - Step 1] 유니 미션 제출합니다.
woowacourse/jwp-mvc pull request #30
Opened 2019-10-04 08:24 UTC by yunheehyeon

2019-10-05 00:25 UTC, pobiconan requested changes
정훈님을 대신해 피드백 남겨요.
미션 요구사항을 지키면서 구현 잘 했네요. 💯 
추가 설계 연습과 테스트 연습을 위해 피드백 남겼어요.

2019-10-05 00:25 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMapping... hm) {
👍

2019-10-05 00:25 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
프레임워크를 구현하는 관점에서 봤을 때 Servlet, Struts1, Struts2와 같은 다양한 프레임워크와의 통합을 하고 싶다.
이와 같이 새로운 기술에 대한 통합을 시도할 경우 if/else가 계속해서 추가될 수 있다.
이와 같이 if/else가 늘어날 것으로 예상되는 부분에 자바의 다형성을 활용해 interface를 추가하고 확장 가능한 구조로 개선해 보면 어떨까?

```
public interface HandlerAdapter {
    boolean supports(Object handler);

    ModelAndView handle(
        HttpServletRequest request, 
        HttpServletResponse response, 
        Object handler) throws Exception;
}
```

2019-10-05 00:25 UTC, pobiconan commented on slipp/src/test/java/slipp/controller/UserControllerTest.java
> +class UserControllerTest {
acceptance test 구현까지 👍

2019-10-05 00:25 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
DispatcherServlet에 대한 테스트 코드도 구현해 본다.
다음 예제 코드와 같이 Spring Test가 제공하는 MockHttpServletRequest, MockHttpServletResponse을 활용해 테스트할 수 있다.

```java
    private DispatcherServlet dispatcher;
    private MockHttpServletRequest request;
    private MockHttpServletResponse response;

    @BeforeEach
    void setUp() {
        dispatcher = new DispatcherServlet();
        dispatcher.init();

        request = new MockHttpServletRequest();
        response = new MockHttpServletResponse();
    }
```

2019-10-05 00:33 UTC, woowahanCU requested changes
안녕하세요! 정훈님이 개인적인 사정이 있어서 대신 리뷰남겨요~ 😀
전반적으로 잘 구현하셨네요. 다만 레벨1 에서 학습했던 클린코드를 위한 지침들이 다소 위배되어 아쉽네요
몇가지 피드백 남겨두었으니 확인해보시고 궁금한 점 있으면 Comment남기시면 포비가 답변주실거에요 😈

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                resp.setStatus(404);
Status Code가 하드코딩 되어 있네요. 상수로 관리하는 것이 좋지 않을까요.
그리고 404가 적절한지도 한번 고민해보세요. 

RequestMapping에 Method를 설정하지 않았을 시에는 요구사항에 있는 것처럼 해당 URL에 대해 모든 Method로 요청할 수 있습니다. 그리고 특정 Method로 설정해두었을 경우 그 외의 Method로 요청시에는 405 로 응답합니다.

https://tools.ietf.org/html/rfc7231#section-6.5.5

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            Object handler = getHandler(req);
HandlerExecution으로 리턴 받는다면 DispatcherServlet에서 if 분기 처리하는 상당부분, instaceof 등이 제거될 수 있겠어요

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      private void move(String viewName, HttpServletRequest req, HttpServletResponse resp)
이 메서드는 현재 두가지 일을 하고 있어 단일책임원칙에 벗어난다고 생각합니다.
RedirectView 등을 작성하여 위임하는 것은 어떨까요

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                        handlerExecutions.put(handlerKey, new HandlerExecution(method, controllers.get(clazz))));
foreach가 3중으로 겹쳐있네요. 작은 기능 단위로 메서드를 분리하여 명확하게 의도를 드러내는 것은 어떨까요

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        }
왜 0일 경우에 전체를 메서드로 넣는건지 의미를 분명하게 드러내는 것이 좋을거 같아요.

2019-10-05 00:33 UTC, woowahanCU commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JsonView.java
> +        return null;
인터페이스를 작성할 때는 구현 클래스에서 모두 메서드로 작성되어야 합니다.
지금의 경우엔 ModelAndView와 JspView간의 결합도가 높은 부분을 감추려하다보니 View 인터페이스에 불필요한 코드가 작성되었고 JsonView에 까지 침범했네요.
DispatcherServlet에서 많은 책임을 담당했기 때문이라고 생각되는데요.
Redirect에 대한 부분은 RedirectView에게, forward하는 부분은 JspView에게 위임하고
기능을 render에 구체적으로 기술한다면 해당 문제는 해결되지 않을까요

2019-10-05 00:33 UTC, woowahanCU commented on slipp/src/main/java/slipp/ManualHandlerMapping.java
> +//        mappings.put("/users", new ListUserController());
사용하지 않는다면 제거해주세요

2019-10-05 00:33 UTC, woowahanCU commented on slipp/src/test/java/slipp/controller/UserControllerTest.java
> +        expected.put("name", "짜바지기");
🤣

2019-10-05 00:33 UTC, woowahanCU commented on study/src/test/java/reflection/Junit4TestRunner.java
>      }
Stream API를 사용할 경우에 Exception을 어떻게 처리해줄지에 대해서도 함께 생각해봐도 좋을거 같아요
https://www.slipp.net/questions/572

2019-10-05 00:33 UTC, woowahanCU commented on study/src/test/java/reflection/ReflectionTest.java
> +                .forEach(method -> logger.debug("method : {}", method));
미션이 출력을 하는 것들 이었지만, 값을 비교하는 테스트를 작성하는 것이 더 좋다고 생각합니다.
테스트 코드를 작성하는 것은 리팩토링하는 과정을 돕기도 하지만, 배포 파이프라인에서도 의미를 갖는다고 생각하는데요.
단순히 출력하는 테스트는 리팩토링 과정에서는 사용자의 확인을 필요로하고, 배포 파이프라인에서는 별다른 의미를 갖지 않게 된다고 생각합니다.

2019-10-05 00:33 UTC, woowahanCU commented on slipp/src/test/java/slipp/controller/UserControllerTest.java
> +class UserControllerTest {
인수테스트만 진행하였는데요. MockHttpServletRequest, MockHttpServletResponse 등을 활용하여 테스트 작성도 가능할거 같아요.

2019-10-05 00:33 UTC, woowahanCU commented on slipp/src/main/java/slipp/controller/UserController.java
> +            throw new NullPointerException("사용자를 찾을 수 없습니다.");
유저가 없을 경우에 NullPointerException이 적절할까요?

2019-10-05 00:33 UTC, woowahanCU commented on slipp/src/main/java/slipp/controller/UserController.java
> +    public ModelAndView userList(HttpServletRequest req, HttpServletResponse resp) throws Exception {
method name은 동작을 구체적으로 드러내는 동사를 사용하시는 것이 좋다고 생각합니다.

http://www.mimul.com/pebble/default/2013/05/04/1367639300999.html

2019-10-06 16:30 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                resp.setStatus(404);
HandlerKey 가 경로와 메소드를 가지고 있어서  404와 405를 구분하려면 어떻게 해야 하는지 잘 모르겠습니다. 힌트 같은 게 있을까요?

2019-10-06 16:34 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            Object handler = getHandler(req);
HandlerExecution 으로 하면 기존의 코드를 상당 부분 바꿔야 할 것 같아서 포비가 제안한 Adapter를 적용했습니다. 잘 적용한 것인지 모르겠습니다.

2019-10-06 16:35 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      private void move(String viewName, HttpServletRequest req, HttpServletResponse resp)
분리했습니다!

2019-10-06 16:35 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                        handlerExecutions.put(handlerKey, new HandlerExecution(method, controllers.get(clazz))));
분리했습니다!

2019-10-06 16:35 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        }
반영했습니다.

2019-10-06 16:36 UTC, yunheehyeon commented on slipp/src/main/java/slipp/ManualHandlerMapping.java
> +//        mappings.put("/users", new ListUserController());
반영했습니다!

2019-10-06 16:37 UTC, yunheehyeon commented on study/src/test/java/reflection/ReflectionTest.java
> +                .forEach(method -> logger.debug("method : {}", method));
반영했습니다.

2019-10-06 16:37 UTC, yunheehyeon commented on slipp/src/main/java/slipp/controller/UserController.java
> +    public ModelAndView userList(HttpServletRequest req, HttpServletResponse resp) throws Exception {
반영했습니다.

2019-10-07 04:14 UTC, yunheehyeon commented on slipp/src/test/java/slipp/controller/UserControllerTest.java
> +class UserControllerTest {
반영했습니다. 한가지 궁금한 부분이 쿼리스트링까지 포함된 URL을 request에 바로 넣는 방법이 있을까요? 지금은 파싱해서 파라미터에 넣어주고 있습니다.

2019-10-07 04:49 UTC, yunheehyeon commented on slipp/src/main/java/slipp/controller/UserController.java
> +            throw new NullPointerException("사용자를 찾을 수 없습니다.");
기존 코드를 변경하지 않으려고 했습니다. AuthorizationException 을 만들어서 변경했습니다.

2019-10-07 06:20 UTC, yunheehyeon commented on study/src/test/java/reflection/Junit4TestRunner.java
>      }
checked exception이 발생했을 때 별도의 로직 처리를 하지 않는 경우라고 생각해서 런타임 예외로 처리해 주었습니다.

2019-10-07 07:04 UTC, yunheehyeon commented on study/src/test/java/reflection/Junit4TestRunner.java
>      }
ControllerScanner 도 예외를 런타임으로 바꿔서 처리했습니다.

2019-10-07 07:09 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JsonView.java
> +        return null;
view 가 다음 단계 미션이라서 최소한으로 변경하려고 했습니다. view가 render를 하도록 분리했습니다.

2019-10-07 07:11 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
재가 이해한 adapter로 바꿔서 구현해봤는데 if가 분산은 되지만 줄어 들지는 않는거 같습니다. 잘 못 이해한 걸까요?

2019-10-07 07:14 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
DispatcherTestHelper 를 만들어서 반영해 봤습니다.

2019-10-07 09:16 UTC, pobiconan requested changes
HandlerAdapter 적용과 관련해 피드백 남겼으니 다시 한번 도전해 보면 좋겠네요. 👍

2019-10-07 09:16 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/ControllerHandlerAdapter.java
> +        if (supports(handler)) {
supports() 메소드는 이곳이 아니라 외부에서 호출하는 것이 맞지 않을까?
이곳에서 호출하는 구조다 보니 if/else가 그대로 존재하는 것이 아닐까?

2019-10-07 09:16 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        adapters = Arrays.asList(new ControllerHandlerAdapter(), new HandlerExecutionHandlerAdapter());
이와 같이 구현할 경우 HandlerAdapter가 고정되어 변경하지 못할 가능성이 높다.
HandlerAdapter 또한 HandlerMapping과 같이 DI를 통해 구현해야 유연성이 높아지지 않을까?

2019-10-07 09:16 UTC, pobiconan commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/RedirectView.java
> +public class RedirectView implements View {
RedirectView를 추가했다면 "redirect:"와 같은 상수가 이곳에 위치하는 것이 어떨까?

2019-10-07 09:16 UTC, pobiconan commented on nextstep-mvc/src/test/java/nextstep/mvc/DispatcherTestHelper.java
> +public class DispatcherTestHelper {
테스트를 위한 Helper를 추가하기 위한 시도 👍

2019-10-08 01:41 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/RedirectView.java
> +public class RedirectView implements View {
RedirectView 는 이미 redirect라는 걸 알고 있는 객체여서 path만 있으면 된다고 생각합니다. 기존에 어댑터에서 결정하던 일를 ViewResolver 객체를 만들고 상수를 관리하도록 변경했습니다.

2019-10-08 10:53 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        adapters = Arrays.asList(new ControllerHandlerAdapter(), new HandlerExecutionHandlerAdapter());
반영했습니다. 궁금한 점은 나중에 어노테이션으로 완전이 통합할 때 기존의 컨트롤러 방식을 지원하지 않는다고 하면 adapter를 지워도 되는 건가요?

2019-10-10 06:24 UTC, jeonghoon1107 requested changes
안녕하세요 유니!
개인적인 사정으로 리뷰가 늦었습니다 ㅠㅠ
전반적으로 깔끔하게 잘 구현해주셨는데 아쉬운 부분이 있어서 몇가지 피드백 남겼어요!
확인부탁드려요 :)
궁금하신 점은 언제든 DM 주세요!

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(declaredObject, new Object[]{request, response});
varargs를 사용할 때는 new Object[]를 해주지 않아도 됩니다 :)
찾아보시고 이해가 되지 않으면 말씀해주세요!

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerKey.java
> +    public boolean checkUrl(String url) {
사용하지 않는 메서드들은 정리하는게 좋을 것 같아요.

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  @WebServlet(name = "dispatcher", urlPatterns = "/", loadOnStartup = 1)
SlippWebApplicationInitializer에 같은 설정이 들어있는 것 같은데, 해당 annotation이 필요한가요?

2019-10-10 06:24 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = new User(req.getParameter("userId"), req.getParameter("password"), req.getParameter("name"),
계층 분리가 하나도 되어있지 않은 것 같아요.
https://wckhg89.tistory.com/13
layer에 대한 부분만 참고하시면 좋을 것 같아요!

2019-10-10 06:24 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = new User(req.getParameter("userId"), req.getParameter("password"), req.getParameter("name"),
user 데이터를 추출하는 부분을 메서드로 빼면 어떨까요?

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
> +    void 유저프로필_조회() throws ServletException {
DisplayName을 활용해보는 것도 좋을 것 같아요!

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        if (requestMethods.length == EMPTY_METHODS) {
http method 가져오는 부분을 분리하면 좋을 것 같아요.

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        log.debug("path: {}", request.getRequestURI());
로그를 한줄로만 남겨도 괜찮을 것 같아요.

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        requestMappingMethods.keySet().forEach(clazz -> turnRequestMappingMethods(controllers, requestMappingMethods, clazz));
메서드의 인자를 줄일 필요가 있어보여요. 불필요하게 map을 계속 인자로 주고 있는 것 같네요.
clazz를 계속 넘기는 이유도 map에서 꺼내는 용도로만 사용하는 것인가요?
`clazz -> turnRequestMappingMethods(controllers.get(clazz), requestMappingMethods.get(clazz))`
등으로 변경해보면 어떨까요?

2019-10-10 06:24 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        Map<Class<?>, Set<Method>> list = new HashMap<>();
다른곳에는 stream으로 만들고 있는데, 여기에서만 forEach를 사용한 이유가 있나요?

2019-10-10 08:14 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(declaredObject, new Object[]{request, response});
반영했습니다!

2019-10-10 08:14 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerKey.java
> +    public boolean checkUrl(String url) {
반영했습니다!

2019-10-10 08:18 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>  @WebServlet(name = "dispatcher", urlPatterns = "/", loadOnStartup = 1)
중복이 되는 annotation이군요. SlippWebApplicationInitializer에서 설정하지 않고 이 annotation을 적용시키는 방법을 알 수 있을까요?

2019-10-10 08:22 UTC, yunheehyeon commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = new User(req.getParameter("userId"), req.getParameter("password"), req.getParameter("name"),
user service를 분리했습니다. 나중에 DI를 구현하면 service를 주입 받도록 수정할 수도 있겠네요

2019-10-10 08:22 UTC, yunheehyeon commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = new User(req.getParameter("userId"), req.getParameter("password"), req.getParameter("name"),
반영했습니다! 시간이 된다면 아규먼트 리졸버를 적용해 볼 수 있겠네요

2019-10-10 08:24 UTC, yunheehyeon commented on nextstep-mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
> +    void 유저프로필_조회() throws ServletException {
반영했습니다.

2019-10-10 08:25 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        if (requestMethods.length == EMPTY_METHODS) {
반영했습니다!

2019-10-10 08:26 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        log.debug("path: {}", request.getRequestURI());
반영했습니다!

2019-10-10 08:28 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        requestMappingMethods.keySet().forEach(clazz -> turnRequestMappingMethods(controllers, requestMappingMethods, clazz));
볼 때마다 이상했는데.. 이렇게 하면 되는군요.. 반영했습니다.

2019-10-10 08:29 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        Map<Class<?>, Set<Method>> list = new HashMap<>();
스트림으로 가능한 부분이었군요.. 반영했습니다!

2019-10-11 10:21 UTC, jeonghoon1107 approved these changes
안녕하세요 유니!
피드백 반영 잘 해주셨네요 👍 
간단한 피드백 남겼으니 다음 미션에 반영해주세요!

2019-10-11 10:21 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +                .collect(Collectors.toMap(clazz -> clazz, clazz -> ReflectionUtils.getAllMethods(clazz, ReflectionUtils.withAnnotation(RequestMapping.class))));
Collectors.toMap에는 세번째 인자로 mergeFunction을 받을 수 있어요!
공부해보시면 좋을 것 같아요 :)

2019-10-11 10:21 UTC, merged