[MVC - Step 1] 뚱이 미션 제출합니다.
woowacourse/jwp-mvc pull request #33
Opened 2019-10-05 06:43 UTC by starkim06

2019-10-07 15:22 UTC, kang-hyungu requested changes
안녕하세요 뚱이 리뷰어 강현구입니다
큰 구조는 잘 잡았네요 👍 
조금더 다듬으면 좋을 부분에 피드백 남겼어요
적용해보시고 재요청주세요!

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                    return adapter.execute(req, resp);
뎁스가 너무 깊은데 줄일 방법 없을까요?
stream을 활용하면 되지 않을까요?

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/main/java/nextstep/mvc/AnnotationHandlerAdapter.java
> +        annotationHandlerMapping.initialize();
외부에서 initialize 하는게 낫지 않을까요?
어댑터 생성자에서 처리할 필요는 없어보여서요

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      public void init() throws ServletException {
init이 하는일이 아무것도 없는것 같네요;;

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/main/java/nextstep/mvc/ManualHandlerAdapter.java
> +        return Objects.nonNull(manualHandlerMapping.getHandler(request));
request를 manual handler mapping과 annotation handler mapping 두 객체에서 동일한 uri, http method를 갖고 있으면 의도한대로 동작하지 않을 것 같네요
ManualHandlerAdapter에서 실행시켜서 ModelAndView를 반환할 객체가 ManualHandlerMapping에서 생성한 객체가 맞는지 확인하려면 어떻게 해야 할까요?

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(method.getDeclaringClass().getDeclaredConstructor().newInstance(), request, response);
규칙 4: 한 줄에 점을 하나만 찍는다.
코드 조금만 정리하면 더 좋을것 같네요!

2019-10-07 15:22 UTC, kang-hyungu commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>          execution.handle(request, response);
의도한 컨트롤러 클래스를 반환했는지 테스트해보면 어떨까요?

2019-10-07 15:22 UTC, kang-hyungu commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        HandlerAdapter[] handlerAdapters = {new ManualHandlerAdapter(manualHandlerMapping), new AnnotationHandlerAdapter(annotationHandler)};
요부분은 dispatcher servlet에서 처리해도 되지 않을까요?

2019-10-08 04:53 UTC, starkim06 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(method.getDeclaringClass().getDeclaredConstructor().newInstance(), request, response);
현재 구조에서는 인스턴스도 매번 생성되는 구조라서 변경하였습니다.

2019-10-08 04:53 UTC, starkim06 commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>          execution.handle(request, response);
테스트 추가하였습니다.!

2019-10-09 06:32 UTC, kang-hyungu commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>          execution.handle(request, response);
테스트 돌려보니 MyUserController에 JspView, RedirectView가 import 되지 않아서 깨지네요
다음 미션 진행하면서 확인해보세요!

2019-10-09 06:45 UTC, kang-hyungu commented
어제 퇴근을 너무 늦게 해서 답변을 못남겼네요;
dm으로 질문 주셨던 3, 4번 답변이에요!

3. 어댑터 객체를 사용하는 클라이언트 코드 입장에서 객체를 초기화하고 싶은 시점을 선택할 수 있게 해둬야 initialize 메서드 역할을 하는게 아닐까요? 객체 생성되자마자 initialize가 실행되면 생성자랑 다른 점이 없는 것 같아요. 객체가 만들어지고 특정 조건을 만족하고 나서 객체 초기화해야되는 경우도 있어요

4. http 응답 코드가 400, 401, 404로 내려오면 해당 응답코드에 대응하면 View를 만들어둬서 그 객체들을 호출하면 되지 않을까요? 나중에 aop로 처리하면 될 것 같아요
HandlerExecution의 역할은 클라이언트, 서버 에러 코드에 대한 처리를 하는건 아닌 것 같아요. HandlerExecution가 맡은 일은 프레임워크 내에서 컨트롤러의 메서드를 실행시키고 적절한 리턴 타입을 반환하는 것이라 봐요

2019-10-09 06:46 UTC, kang-hyungu approved these changes
피드백 반영 잘 하셨어요! 👍 
dm으로 따로 질문 주신 내용들중에 답변 못드렸던 부분은 코멘트 남겼으니 참고하세요
코드 구현하느라 수고하셨어요!

2019-10-09 06:46 UTC, merged

2019-10-09 07:18 UTC, starkim06 commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
>          execution.handle(request, response);
넵.. 확인하고 수정하겠습니다. 죄송합니다