[MVC - step1] 코맥 미션 제출합니다.
woowacourse/jwp-mvc pull request #34
Opened 2019-10-05 07:13 UTC by CODEMCD

안녕하세요! 리뷰이 코맥입니다.

- 기존 레거시 코드 `ManualHandlerMapping`은 `Controller`를 반환하고, 리펙토링하는 코드 `AnnotationHandlerMapping`은 `HandlerExecution`을 반환하고 있습니다. 이 두 핸들러매핑 클래스는 `HandlerMapping` 인터페이스를 구현하고 있는데, 이를 통합하고자 `getHandler()` 메서드 반환값을 Object로 통일하였습니다.
- 그리고 각각 핸들러 매핑 클래스를 처리해주는 Adapter를 만들었습니다.(`ManualHandlerAdapter`, `AnnotationHandlerAdapter`)
- 각 Adapter는 핸들러 매핑을 가지고 있으며, `execute()`메서드에서 클라이언트 요청을 처리해주는 클래스(`Controller` 또는 `HandlerExecution`)를 호출합니다.
- 각 Adapter는 `isSupported()` 메서드를 구현하여 `DispatcherServlet` 클래스에서 클라이언트 요청이 어떤 Adapter로 처리할 수 있는지 알 수 있도록 하였습니다.
- 클라이언트 요청 처리 순서는 대략적으로 `DispatcherServlelt` -> `HandlerAdapter` -> `HandlerMapping` -> `Handler`(`Controller` 또는 `HandlerAdapter`) -> `ModelAndView` 입니다.

`if-else` 문을 제거하면서 구현한 과정을 대략적으로 정리해보았습니다. 부족한 부분이 많습니다...아낌없는 지적 부탁드립니다. 감사합니다!!

2019-10-05 14:49 UTC, hongsii requested changes
안녕하세요 코맥!
요구사항을 잘 구현해주셨습니다! 💯 
간단한 피드백 몇 가지 드렸으니, 확인하시고 반영해주세요!

2019-10-05 14:49 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +            putHandlers(method, annotation, requestMethods);
`RequestMapping` 을 파라미터로 `RequestMethod[]` 를 반환하는 메서드가 있다면 이 메서드의 가독성이 조금 더 좋아질 수 있을 듯 합니다.

2019-10-05 14:49 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/RedirectView.java
> +public class RedirectView implements View {
View 활용 👍

2019-10-05 14:49 UTC, hongsii commented on study/src/test/java/reflection/ReflectionTest.java
> +        }
`getDeclaredField(name)` 를 활용하면 원하는 필드만 얻을 수 있습니다.

2019-10-05 14:49 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(method.getDeclaringClass().getDeclaredConstructor().newInstance(), request, response);
`HandlerExecution` 이 실행될 때마다 메서드의 인스턴스가 생성되고 있습니다. 인스턴스를 한 번만 생성하도록 바꿔보면 어떨까요?

2019-10-05 14:49 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    private ModelAndView getModelAndView(HttpServletRequest req, HttpServletResponse resp) {
메서드의 네이밍이 모호한 것 같아요. 좀 더 명확한 네이밍으로 바꿔보면 어떨까요?

2019-10-07 12:01 UTC, CODEMCD commented on study/src/test/java/reflection/ReflectionTest.java
> +        }
피드백 감사합니다! 적용해보았습니다.

2019-10-07 12:26 UTC, CODEMCD commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +            putHandlers(method, annotation, requestMethods);
피드백 감사합니다!

말씀대로 한 결과 불필요한 `if` 문을 제거할 수 있었고, 코드가 더 간결해졌습니다.

2019-10-07 12:59 UTC, CODEMCD commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(method.getDeclaringClass().getDeclaredConstructor().newInstance(), request, response);
피드백 감사합니다!

이 부분에 대해서는 생각을 못했었습니다. `HandlerExecution` 객체를 만들 때 해당 핸들러 오브젝트를 같이 전달하는 방식으로 변경하였습니다.

2019-10-07 13:18 UTC, CODEMCD commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    private ModelAndView getModelAndView(HttpServletRequest req, HttpServletResponse resp) {
피드백 감사합니다!

현재 `getModelAndView()` 메서드는 `HandlerAdapter` 를 찾아서 `handle()` 메서드를 호출하는 역할을 합니다. 따라서 이러한 역할을 나타내는 `doHandle()` 로 변경하였습니다.

2019-10-07 14:03 UTC, hongsii approved these changes
피드백 반영을 잘해주셔서 코멘트 드릴게 없네요 💯 
다음 단계 진행해주세요 :)

2019-10-07 14:04 UTC, merged