[MVC - Step 1] 제이 미션 제출합니다.
woowacourse/jwp-mvc pull request #4
Opened 2019-10-02 04:50 UTC by JunHoPark93

안녕하세요 쏘쏘님! 😀리뷰이 제이 입니다.
Annotation 기반 컨트롤러를 메인페이지 이동(get), 로그인 페이지 이동(get), 회원 가입(post) 에 적용시켜 보았습니다.
레거시 컨트롤러 매핑과 애노테이션 컨트롤러 매핑을 어떻게 통합할지 고민하다가 
변경할 레거시 컨트롤러를 제외한 기존의 레거시 컨트롤러의 코드를 아예 건드리지 않고 리팩토링 하는 방향으로 해보았습니다. 그래서 view resolver에서 String을 검사 (레거시 컨트롤러의 반환 값) 했습니다. 결과적으로 dispatcher servlet 에서 ModelAndView만으로 핸들링하게끔 변경하였습니다.
ViewResolver에 instance of를 없애고 싶었으나 기존 레거시 컨트롤러의 반환 값을 전부 변경해야 하는게 점진적인거 같지 않아서 사용을 하였는데 괜찮을까요.

항상 감사드립니다!

2019-10-03 00:27 UTC, ssosso requested changes
제이! 미션 잘 수행해 주셨네요. 💯 
뷰 구조로만 일관되게 가는 구조도 괜찮지만 한계점이 보여서 코멘트 드렸습니다.
간단한 피드백이니 확인하시고 반영 부탁드릴게요~!

2019-10-03 00:27 UTC, ssosso commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                .map(handlerMapping -> handlerMapping.getHandler(req))
자바의 한계? 이기도 하지만 함수형의 사용을 위해 `handlerMapping.getHandler(req)` 두번 호출하는 성능적인 관점에서 불필요해 보입니다. 큰 성능을 잡아먹는건 아니지만 약간 개발자의 기본 소양같은 느낌으로...두번 호출하는건 필요가 없어 보이네요:)

2019-10-03 00:27 UTC, ssosso commented on nextstep-mvc/src/main/java/nextstep/mvc/ViewResolver.java
> +    public static ModelAndView resolve(Object object) {
지금이야 `ModelAndView`로 모두 처리 가능하지만 Rest API를 제공하는 관점에서 다양한 클래스 오브젝트, String 기타 등을 지원하려면 계속 분기처리가 늘어날 듯 합니다. 뷰에 해당할 때만 변경하는게 좋아보이네요.

2019-10-04 04:31 UTC, JunHoPark93 commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                .map(handlerMapping -> handlerMapping.getHandler(req))
넵! 순서가 잘못되었었습니다ㅠ 반영하였습니다!!

2019-10-04 04:36 UTC, JunHoPark93 commented on nextstep-mvc/src/main/java/nextstep/mvc/ViewResolver.java
> +    public static ModelAndView resolve(Object object) {
바로 다음 2단계 미션에서 JsonView를 구현하는 부분이 있는데 그 때 적용해서 PR 보내는 것으로 해보겠습니다!
1단계 까지는(현재) HandlerAdapter에서 JspView를 넣어서 실행되는 종속적인 구조로 되었는데, 다음 단계에서 바로 개선해보겠습니다!

2019-10-04 04:40 UTC, JunHoPark93 commented
안녕하세요 쏘쏘님! 피드백 반영하고 조금 더 개선해보았습니다.

## Handler Adapter 적용
적용이유: handler에서 받은 결과 값들을 분기문을 타면서 instance of 로 검사하는 로직을 개선하기 위해서 추상화를 해보았습니다.

## class new instance 개선
AnnotationHandlerMapping 클래스의 addHandlerExecution 메서드에서 포문에서 매번 new instance하는 부분을 개선하였습니다.

```java
 Object instance = createInstance(clazz);
 Arrays.stream(requestMethods)
                    .map(value -> new HandlerKey(requestMapping.value(), value))
                    .forEach(key -> handlerExecutions.put(key, new HandlerExecution(instance, method)));
```

## Step2 TODO
현재 modelandview 에서 render를 하게 되는데, 2단계를 해보면서 view 의 종류에 따라서 render가 되게 개선해보겠습니다.

2019-10-05 00:13 UTC, ssosso approved these changes
제이! 리뷰를 잘 반영해 주셨네요 💯 
머지하겠습니다! 다음 미션 부탁해요:)

2019-10-05 00:13 UTC, merged