[MVC-Step 1] 러너덕 미션 제출합니다.
woowacourse/jwp-mvc pull request #40
Opened 2019-10-06 13:01 UTC by Deocksoo

안녕하세요 킹뽀대님, 이번 미션 리뷰이 러너덕입니다.
이번 미션에서는 기존 코드들이 변경되지 않도록 하면서 새로운 기능으로 리펙토링하는 연습을 해보았습니다. 리펙토링하는 과정에서 이름을 참 많이 고민하게 되는데요, 적절한 이름들을 잘 골랐는지 모르겠습니다. 
테스트도 아직 부족한 부분이 있지만 일단 피드백을 한번 받아보고싶어서 요청 보내드려요. 많은 조언 부탁드립니다 :)

2019-10-07 10:41 UTC, kingbbode requested changes
안녕하세요! 
몇 가지 코멘트 작성하였습니다 :) 
확인 부탁드립니다.

2019-10-07 10:41 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>          }
1. try - catch 의 예외 모델을 사용한 분기처리를 하셨네요. NotFoundHandlerException 은 어느 레이어에게 전파하기 위해 설정된 예외인가요? 이 예외가 DispatcherServlet 에서 일관성을 가져갈 수 있는 형태인가요? 분기를 위한 처리라면 불필요하고 과하다고 생각이 듭니다.

2. 기존 코드는 전혀 손대지 않고 호환하도록 하려는 의도였을까요? Adapter 를 가져가는 계층이 모호한 것 같아요 :) DispatcherServlet이 레거시와 새로운 모델의 구현을 알도록 설계하는 것은 추후 확장에 큰 불편함으로 돌아올 것 같아요.

2019-10-07 10:41 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        connectHandler(annotation, execution);
requestMethods 가 1개이든 2개이든 존재하지 않든 일관된 작성이 가능할 것 같네요 :)
분기가 되어야할 것은 이 한 부분이지 않을까요?
```
requestMethods.length == 0 ? RequestMethod.values() : requestMethods
```

2019-10-07 10:41 UTC, kingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        this.instance = getInstance(clazz);
인스턴스를 HandlerExecution 마다 생성되지 않고 효율적으로 생성할 수 있지 않을까요?

2019-10-07 10:41 UTC, kingbbode commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/AnnotationHandlerMappingTest.java
> +        Method expectedMethod = getControllerMethod(MyController.class, "handleOneRequestMethod");
코드가 조금이라도 수정되면 테스트가 많이 깨지겠네요.
검증 방식과 기대 값에 대한 설정을 다시 고려해보는 것이 좋을 것 같습니다.

2019-10-07 10:43 UTC, kingbbode commented
테스트 대상과 검증 방식에 대한 고찰을 많이 해보셨으면 합니다.

모든 클래스를 테스트 하려다보니, 테스트가 너무 많은 구현을 알고 있게 되었다고 생각되네요.
무엇을 테스트해야하고 어떤 것을 검증해야할지 다시 한번 생각해보시는게 좋을 것 같습니다.

2019-10-08 06:53 UTC, Deocksoo reviewed
좋은 리뷰 너무 감사합니다! 특히 테스트 코드를 작성하면서 찜찜했던 부분들이 많은데, 어떻게 테스트하는 것이 좋을지 더 고민해보겠습니다!

2019-10-08 06:53 UTC, Deocksoo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        connectHandler(annotation, execution);
RequestMethod를 지정하지 않은(모든 RequestMethod를 지원하는) 컨트롤러 메소드를 등록할 때, 기존에 등록되어있는 컨트롤러 메서드가 있는지 확인하고 등록하는 과정이 없으면 앞서 ReqeustMethod를 지정해서 등록한 컨트롤러 메서드가 있는 경우 덮어 쓰게 되지 않을까요? 말씀해주신 것처럼 깔끔하게 처리하고 싶은데, 이 부분때문에 처리가 조금 까다로워요. (제가 제시해주신 방향을 잘 이해한것이 맞나요..?)

2019-10-08 06:53 UTC, Deocksoo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/HandlerExecution.java
> +        this.instance = getInstance(clazz);
HandlerExecution은 매핑시에 url과 RequestMethod에 따라 보통 하나씩만 생성하여 매핑하니 크게 효율이 떨어지지 않을 거라고 생각했는데, 좀더 생각해보니 하나의 컨트롤러에 메서드를 여러개 만들면 메서드마다 같은 컨트롤러가 중복해서 생성되면서 효율이 떨어지겠군요. 수정하겠습니다!

2019-10-08 06:53 UTC, Deocksoo commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>          }
1. 이 부분에서 try-catch를 사용했던 이유는 annotationHandlerMapping에서 handler를 찾지 못했을 경우에 null을 되돌려주는 것이 찜찜해서 분기를 위해 예외처리를 했어요. 하지만 말씀해주신 것처럼 분기를 위한 처리라 불필요한 예외인것 같아요. 어떻게 수정하는 것이 좋을지 조금 더 고민해보겠습니다!

2. 리펙토링할 때 제가 레거시 코드를 어디까지 수정해도 될지 감이 오지 않아서 Adapter를 애매하게 사용하게 된것 같아요. 이 부분을 수정해보고 싶은데 Adapter를 가져가는 계층이 모호하다는 말씀을 제가 잘 이해하지 못했어요. 이 부분을 혹시 조금만 더 부연해서 설명해주실 수 있을까요?

2019-10-10 13:16 UTC, Deocksoo commented
피드백 남겨주신 부분을 중심으로 코드를 정리해봤는데, 깔끔하게 정리하기가 쉽지 않네요. 아직 미흡한 부분들이 남아있는거 같아요, 많은 지적 부탁드립니다.
그리고 기존 테스트 코드에서 너무 많은 구현을 알고 있다는 말씀을 해주셔서 테스트 관련 코드들을 조금 찾아보면서 고민해보았는데요, 리플렉션을 사용해서 클래스 구현체에 직접 접근하는 코드들이나, HandlerExecutionTest와 같은 테스트들이 과했던 것이 아닌가 싶어 수정해보았습니다. 
제출이 조금 늦었지만 다시한번 리뷰 부탁드립니다, 감사합니다 :)

2019-10-11 11:35 UTC, woowahankingbbode approved these changes
리뷰가 많이 늦었습니다!
1단계에서 필요한 내용은 모두 만족한 것 같아요.
2단계에서도 잘 부탁드려요! :)

2019-10-11 11:35 UTC, woowahankingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            HandlerAdapter handler = getHandlerOf(request);
Handler 없이 HandlerAdapter 가 존재하는게 이상하네요 :)
Adapter 는 기존 결과물의 변경없이 새로운 구조와 연결이 될 수 있다는 의미를 가지고 있습니다.
의도하신 네이밍과 일치하는지 생각해보시면 좋을 것 같습니다!

2019-10-11 11:35 UTC, woowahankingbbode commented on nextstep-mvc/src/main/java/nextstep/utils/LoggingUtils.java
> +    public static void logStackTrace(Logger logger, Exception e) {
이미 로거 구현체에서 하고 있는 일을 직접 구현하려고 하는 것 같아요.
로거 구현체의 사용법을 좀 더 알아보시는 것이 좋을 것 같아요.

2019-10-11 11:35 UTC, woowahankingbbode commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/scanner/ControllerScanner.java
> +public class ControllerScanner {
좋은 분리네요 :)

2019-10-11 11:40 UTC, woowahankingbbode commented
처음 작성하신 형태의 추상화가 더 좋아보이네요 :)
계층이 모호하다고 말씀드린 어렵게 이야기된듯 하네요 ㅜㅜ 

새로운걸로 꽂아보고 안되면 기존 것으로 꼽아! 가 아니고 어뎁터를 가져갔다면 새로운 것과 기존 것을 구분하지 않아야한다는 의도로 말씀드렸는데 답변을 못했네요 ㅜㅜ

2019-10-11 11:46 UTC, woowahankingbbode commented
`ReqeustMethod를 지정해서 등록한 컨트롤러 메서드가 있는 경우 덮어 쓰게 되지 않을까요?`

위 부분은 RequestMethod 가 모두일 뿐만 아니라 모든 경우에 대해서도 확인이 필요한 부분이지 않을까요?

```
for (RequestMethod requestMethod : connectable) {
            handlerKey = new HandlerKey(uri, requestMethod);
            handlerExecutions.put(handlerKey, execution);
        }
```

제가 보기에는 이 단계에서 처리해야할 문제인 것 같아요 :) 이렇게 보면 `connectHandlerToAllConnectableRequestMethods` 과 `connectHandler` 이 중복된 일을 하고 있는게 느껴지실까요?

2019-10-11 11:46 UTC, woowahankingbbode commented
고민이 많으셨을텐데 코멘트 답글로 달렸을 때 이메일이 너무 많이와서 다 확인할 수가 없었네요  ㅜㅜ
다음에는 고민이 생기시면 슬랙 DM 으로 코멘트 달았어요! 라고 보내주시면 감사하겠습니다 ㅜㅜ

2019-10-11 11:47 UTC, merged

2019-10-13 07:12 UTC, Deocksoo commented on nextstep-mvc/src/main/java/nextstep/utils/LoggingUtils.java
> +    public static void logStackTrace(Logger logger, Exception e) {
이미 로거에 있는 기능이었네요..! 구현되어있는 기능을 사용하는 것이 더 좋을것 같아 수정했습니다 :)