[MVC - Step 2] 제이 미션 제출합니다
woowacourse/jwp-mvc pull request #46
Opened 2019-10-07 11:56 UTC by JunHoPark93

안녕하세요 쏘쏘님, 2단계 제출합니다. 
이번 단계에서는 view resolver 구현과 전부 annotation 기반 컨트롤러로 변경해보았습니다.
부족하지만 잘 부탁드리겠습니다! 🥺 감사합니다!

2019-10-07 23:53 UTC, ssosso requested changes
제이! 전반적으로 깔끔하게 짜주셔서 코멘트할 부분이 많이 없네요. 💯 
몇 가지 개선점에 대해서는 의견 주시거나 반영 부탁드릴게요~!

2019-10-07 23:53 UTC, ssosso commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/JsonView.java
> +        ObjectMapper objectMapper = new ObjectMapper();
랜더할때마다 인스턴스를 새로 만들겠네요. 필드나 다른 util class에 저장해서 재활용하는 방식은 어떨까요?

2019-10-07 23:53 UTC, ssosso commented on nextstep-mvc/src/main/java/nextstep/utils/JsonUtils.java
> +        ObjectMapper objectMapper = new ObjectMapper();
여기도 인스턴스 매번 생성 이슈!

2019-10-07 23:53 UTC, ssosso commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/viewresolver/JsonViewResolver.java
> +public class JsonViewResolver implements ViewResolver {
ViewResolver -> Resolver or ResponseResolver
가 맞지 않을까요?

2019-10-07 23:53 UTC, ssosso commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/TestUserController.java
>          return mav;
무조건 `ModelAndView`를 반환하는게 어색합니다.
`ViewResolver`의 `support` 메서드에서 타입 체크를 통해 처리하는건 어떨까요?
예를들어 `ModelAndView`이면 JspViewResolver로 나머지 타입은 JsonViewResolver로 처리와 같은 식으로요:)

2019-10-08 14:51 UTC, JunHoPark93 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/JsonView.java
> +        ObjectMapper objectMapper = new ObjectMapper();
넵! objectmapper를 한 번만 생성하게 변경했습니다!

2019-10-08 14:51 UTC, JunHoPark93 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/viewresolver/JsonViewResolver.java
> +public class JsonViewResolver implements ViewResolver {
말씀 주신대로 Json은 view 가 없기 때문에 변경하는게 맞는것 같습니다

2019-10-08 14:56 UTC, JunHoPark93 commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/TestUserController.java
>          return mav;
저 클래스는 clone 당시 존재하던 코드여서 미션과는 상관없는 부분이었는데, ModelAndView 생성자를 변경하면서 기존에 있던 mav 초기화부분만 고친 것입니! 혹시 저 컨트롤러를 void 로 변경하라는 말씀이신지 궁금합니다!

2019-10-08 14:57 UTC, JunHoPark93 commented
바쁘신 와중에 빠른 피드백 감사합니다!!! 피드백 주신 내용들 반영해보았습니다!
감사합니다!!ㅎㅎ

2019-10-09 03:24 UTC, ssosso commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/TestUserController.java
>          return mav;
앗, 제가 잘못 이해했었네요, 해당 피드백은 지나치셔도 됩니다:)

2019-10-09 03:26 UTC, ssosso approved these changes
답글 달아주신 부분 확인하였습니다:)
제가 잘못 이해하고 말씀드린 부분도 있었네요, 스킵하셔도 됩니다:)
다음 단계 진행하실 수 있다고 판단됩니다:) 화이팅~

2019-10-09 03:26 UTC, merged