[MVC - step2] 닉 미션 제출합니다.
woowacourse/jwp-mvc pull request #49
Opened 2019-10-08 08:57 UTC by wbluke

안녕하세요 화투 :) 이번 주차도 잘 부탁드립니다!

- Jackson에 대한 학습 테스트를 learningtest 패키지에 추가하였습니다.
- UserAcceptanceTest를 통과시키기 위한 Controller는 UserApiController로 두었습니다.
- 기존 MVC 프레임워크의 Controller들을 어노테이션 기반의 MVC 프레임워크로 변경하여 이동하고, 레거시 로직을 전부 삭제하였습니다.

2019-10-09 17:10 UTC, phs1116 requested changes
안녕하세요! 닉.
JsonView 구현 및 유틸성 클래스들 분리 👍 
구현 너무 잘해주셨어요.
간단한 피드백 몇가지 추가했는데 참고 부탁드릴게요. :)

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/JsonView.java
> +        response.setContentType("application/json");
ContentType이 두번 셋팅되고있네요 :)

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/ModelAndView.java
> +    public static final class ModelAndViewBuilder {
ModelAndView에 이미 addObject라는 메서드가 있는데  해당 빌더가 필요한가요..??

2019-10-09 17:10 UTC, phs1116 commented on slipp/src/main/java/slipp/controller/UserApiController.java
> +        resp.setStatus(HttpServletResponse.SC_OK);
200을 매번 셋팅할 필요가 있을까요? :)

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/resolver/ArgumentResolver.java
> +public class ArgumentResolver {
ArgumentResolver가 기존 Spring의 ArgumentResolver와 횬동 될 여지가 있네요.

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/resolver/ArgumentResolver.java
> +        return JsonUtils.toObject(body, clazz);
굳이 body를 String 형태로 만들지 않아도 objectMapper에서는 inputStream을 전달해서도 컨버팅이 가능합니다. :)
`readValue(InputStream src, Class<T> valueType)`

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/test/java/nextstep/learningtest/JacksonTest.java
> +        System.out.println(cars);
테스트더라도 System.out.println은 최대한 안쓰도록 습관들이는게 좋을 것 같아요. :)

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/test/java/nextstep/learningtest/JacksonTest.java
> +        Car car = objectMapper.readValue(new File(TARGET_PATH + "/blue_car.json"), Car.class);
테스트에 검증 또한 있어야하지 않을까요?

2019-10-09 17:10 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/web/support/ResponseLocationBuilder.java
> +public class ResponseLocationBuilder {
URI에 대해서 보편적으로 사용할 수 있는 기능인 것 같은데
ResponseLocationBuilder 처럼 Response에만 한정짓지 말고 URIBuilder 같이 보편적으로 사용할 수 있도록 하면 좋을 것 같아요. :)

2019-10-09 17:10 UTC, phs1116 commented on slipp/src/main/java/slipp/controller/UserApiController.java
> +        resp.setHeader("Location", location);
보편적인 헤더는 상수로 관리하면 어떨까요?

2019-10-10 01:48 UTC, wbluke commented on nextstep-mvc/src/test/java/nextstep/learningtest/JacksonTest.java
> +        System.out.println(cars);
학습테스트라는 목적에 맞게 빠르게 API 학습에만 치중하는거니까 괜찮겠지...라고 안일하게 생각했었는데;;ㅎㅎ 수정하였습니다! :)

2019-10-10 04:34 UTC, wbluke commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/ModelAndView.java
> +    public static final class ModelAndViewBuilder {
addObject()가 당연히 void 리턴 타입인줄 알고 그렇게 쓰다가 빌더를 만들면 편하게 쓸 수 있겠다 싶어서 만들었는데... void가 아니라 ModelAndView 리턴이었네요ㅠㅠ 왜 제대로 못봤을까요ㅠㅠ 수정하였습니다!

2019-10-10 04:37 UTC, wbluke commented
늦은 시간에도 리뷰 감사합니다ㅠㅠ! 주신 코멘트 기반으로 수정하였습니다ㅎㅎ
다시 한 번 잘 부탁드립니다 :)

2019-10-11 16:58 UTC, phs1116 approved these changes
안녕하세요! 닉!
피드백 반영 👍 
테스트도 매우 꼼꼼하게 잘 작성해주셨어요! :)
이번 단계 이만 머지할게요.
구현하시느라 정말 수고 많으셨습니다!!! :)

2019-10-11 16:58 UTC, merged