[MVC - Step 2] 코니 미션 제출합니다
woowacourse/jwp-mvc pull request #56
Opened 2019-10-09 12:38 UTC by choihz

안녕하세요, 다시 리뷰 요청 드립니다. 😀

1. 처음엔 `@RequestBody`, `@ResponseBody` 등을 구현하려고 시도했는데, 하다 보니 생각보다 어려운 부분이 많고 시간도 너무 오래 걸려서 우선 이 부분은 제외하였습니다.
2. 현재 `ViewResolver`는 `ModelAndView`가 가진 `viewName`이 "redirect:"로 시작하거나 ".jsp"로 끝날 때 `JspView`를 이용하고 `viewName`이 비었으면 `JsonView`를 이용합니다. api 컨트롤러에서도 `ModelAndView`를 리턴하는 구조이다 보니 이렇게 되었는데, 그래도 이 구조 안에서 개선할 수 있는 방법이 있을지 질문을 드리고 싶어요.
3. 그 외에도 아낌없는 지적과 피드백 부탁드려요. 항상 감사합니다!

2019-10-10 09:31 UTC, hongsii requested changes
2단계도 잘 구현해주셨습니다 👍 
몇 가지 피드백 드렸으니, 확인하셔서 반영해주세요!

2019-10-10 09:31 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        response.getWriter().write(modelAsString);
`ObjectMapper` 는 아래와 같이 `OutputStream` 또는 `Writer` 를 파라미터로 받을 수 있는 메서드를 제공합니다.
해당 메서드를 사용해 리팩토링해보면 어떨까요?

* [ObjectMapper#writeValue](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html#writeValue(java.io.Writer,%20java.lang.Object))

``` java
public void writeValue(Writer w, Object value) throws ...
```

2019-10-10 09:31 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/resolver/JspViewResolver.java
> +        return viewName.startsWith(REDIRECT_PREFIX) || viewName.endsWith(JSP_SUFFIX);
redirect는 jsp가 아닌 다른 템플릿을 사용할 때에도 사용할 수 있으니 `JspView` 에서 분리해보면 좋을 것 같아요.

2019-10-10 09:31 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
> +    private String viewName = "";
지금처럼 `viewName` 으로 직접 타입 및 이름을 변경해버리면 기존 View를 직접 설정하던 유저에 대한 호환성이 깨져버립니다.
`View` 를 직접 설정할 수도 있거나 viewName만 설정하는 경우에 view를 만들어주는 방식으로 바꿔보면 어떨까요?

2019-10-11 07:30 UTC, choihz commented
안녕하세요 홍시님! 피드백 감사하고, 전부 반영해 보았습니다. 다만 `ModelAndView`의 피드백을 제가 잘 반영한 것인지 모르겠어요.

1. `ModelAndView`가 `Object view`라는 필드를 가지게 되었습니다. 생성자에서 `View`를 받든 `String viewName`을 받든 모두 여기에 저장하게 될 텐데요, 이렇게 `Object` 타입을 필드로 가지면 명확하지 않고 모호성이 생기는 것 같아서요. 좋은 방법일까요?
2. 원래 로직은 `ViewResolver`가 `viewName`을 보고 적합한 `View` 타입을 판단해 처리하는 것이었는데, `String viewName`이 `Object view`로 바뀌다 보니 `viewResolver`에서 `null` 체크를 하게 되었어요. 그런데 `null` 체크를 하는 코드는 항상 나쁜 걸까요? 항상 `null`을 보면 `Optional`로 바꾸거나 로직을 바꿔야 하는 것이 아닌지 찜찜해지는데, 이 느낌이 맞는 것인지 궁금합니다. 우선 `Optional`은 필드로 가지는 것이 좋지 않은 것으로 알고 있어서 이번에는 이렇게 구현했고요.

이외에도 제가 놓치고 있는 부분, 고치면 더 좋아질 부분, 더 배우면 좋을 내용이 있다면 다 알려주세요. 항상 감사합니다~☺️

2019-10-11 15:28 UTC, hongsii requested changes
코니 피드백 반영을 잘해주셨어요! 👍 
마지막으로 간단한 피드백 드렸으니, 확인하시고 반영해주세요 :)

2019-10-11 15:28 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/resolver/RedirectViewResolver.java
> +        return view != null && ((String) view).startsWith(REDIRECT_PREFIX);
1. `Object` 타입을 사용함으로써 타입을 알 수 없어 모호해지는 부분이 생깁니다. 하지만, 추후 `view` 필드에 `String`, `View` 뿐만 아니라 새로운 타입이 추가되는 경우에 호환성 및 확장성이 보장된다는 장점이 있습니다. 이처럼 모든 설계에는 트레이드 오프가 존재하기 때문에 항상 옳은 설계는 없고, 상황에 맞춰 적절히 설계해야할 필요가 있습니다! (저도 이 부분은 항상 어렵네요..)
`Object` 타입을 사용하는 경우 필드를 가진 `ModelAndView` 객체에게 메시지를 보내도록 만든다면 사용하는 쪽에서는 구체적인 타입을 받을 수 있게 처리할 수 있습니다.
예를 들어, `viewName`이 필요하다면 아래와 같은 메서드를 만들어 제공한다면 사용하는 쪽에선 모호한 부분 없이 좀 더 편하게 사용할 수 있습니다.

``` java
public String getViewName() {
    return (view instanceof String) ? (String) view : "";
}
```

2. null 체크를 하는 코드가 항상 나쁜 코드가 아니라고 생각합니다. 필요한 경우에는 반드시 null 체크를 통해 오류가 발생하는 것을 방지하는게 우선입니다.
말씀하신대로 `Optional` 은 결과를 반환할 때 null을 반환하는 것을 대체하기 위한 용도로 설계되었기 때문에 필드로 사용하지 않으신 것은 잘하셨습니다 👍 
null로 초기화되는 경우에는 default/empty 값 등으로 초기화해준다면 null이 할당되는 것을 막을 수 있습니다.

2019-10-11 15:28 UTC, hongsii commented on nextstep-mvc/src/main/java/nextstep/mvc/resolver/ViewResolver.java
> +    boolean supports(Object view);
`ModelAndView` 객체로 메시지를 보내도록 리팩토링해보면 어떨까요?

2019-10-13 02:22 UTC, choihz commented
안녕하세요.
주신 예시 코드를 바탕으로 리팩토링을 하였습니다. 그리고 질문에 대한 답변이 정말 큰 도움이 되었어요! 감사합니다. 😄

2019-10-13 05:04 UTC, hongsii approved these changes
피드백을 반영을 잘해주셨습니다 👍 
2단계까지 고생많으셨습니다! 머지하겠습니다 :)

2019-10-13 05:13 UTC, merged