[MVC - Step 2] 효오 미션 제출합니다.
woowacourse/jwp-mvc pull request #59
Opened 2019-10-10 04:48 UTC by hyojaekim

안녕하세요. 효오입니다.

pr 보내고 계속해서 테스트 추가하고, ViewResolver, ArgumentResolver 를 구현할 예정입니다.

항상 좋은 리뷰 주셔서 감사합니다! :)

2019-10-11 10:10 UTC, jeonghoon1107 requested changes
안녕하세요 효오!
코드가 깔끔하네요 💯 
몇가지 피드백 남겼으니 확인부탁드려요 :)

2019-10-11 10:10 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JsonView.java
> +    private String toJson(Map<String, ?> model) throws JsonProcessingException {
JsonUtils라는 클래스가 있는데 해당 클래스로 옮겨보면 어떨까요 :)

2019-10-11 10:10 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/controller/HomeController.java
> +        request.setAttribute("users", DataBase.findAll());
layer 를 분리해보면 어떨까요?
https://wckhg89.tistory.com/13 (layer 부분만 참고하셔서 보면 좋을 것 같아요!)

2019-10-12 09:48 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JsonView.java
> +    private String toJson(Map<String, ?> model) throws JsonProcessingException {
놓친 부분이 있었네요! 피드백 감사합니다.

2019-10-15 09:00 UTC, hyojaekim commented on slipp/src/main/java/slipp/controller/HomeController.java
> +        request.setAttribute("users", DataBase.findAll());
Service Layer 만드려고 생각은 했으나, MVC 프레임워크에 집중하려고 했습니다!
일단 모든 Service Layer를 만들지 않고, 추가 미션으로 ArgumentResolver를 적용해봤습니다.

2019-10-15 09:03 UTC, hyojaekim commented
안녕하세요. 정훈님!
이번에 MVC 프레임워크를 구현하면서 요구사항 외에 다른 것들을 구현하려고 노력해봤습니다.
ArgumentResolver를 만들었는데 이게 맞는건지 잘 모르겠네요..
시간이 걸릴까봐 일단은 Service Layer는 일부만 만들고 제출하고, 계속해서 리팩토링 하겠습니다.

2019-10-16 11:59 UTC, jeonghoon1107 requested changes
안녕하세요 효오!
깔끔하네요 👍 
몇가지 피드백 남겼으니 확인부탁드려요 :)

2019-10-16 11:59 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ArgumentResolver.java
> +        if (parameter.isAnnotationPresent(RequestParam.class)) {
ArgumentResolver 역시 handlerAdapters와 같이 interface로 구현하면 추가될 때마다 분기를 없앨 수 있을 것 같아요!

2019-10-16 11:59 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ArgumentResolver.java
> +    public Object[] resolve(Method method) {
parameter type이 맞지 않으면 4xx 예외를 주는 것은 어떨까요?

2019-10-16 11:59 UTC, jeonghoon1107 commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/ArgumentResolverTest.java
> +public class ArgumentResolverTest {
조금 더 다양한 케이스가 있으면 좋을 것 같아요!

2019-10-16 11:59 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/handlerAdapter/HandlerExecutionHandlerAdapter.java
> +        return (ModelAndView) result;
type casting하지 않아도 handle의 return이 ModelAndView인 것 같은데 맞나요??

2019-10-18 08:12 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/handlerAdapter/HandlerExecutionHandlerAdapter.java
> +        return (ModelAndView) result;
같이 수정을 했어야 했는데 피드백 감사합니다!

2019-10-19 08:40 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ArgumentResolver.java
> +        if (parameter.isAnnotationPresent(RequestParam.class)) {
HandlerAdapter 처럼 interface로 구현을 했는데,
ArgumnetResolver의 Adapter들이 네이밍이 적절한지 궁금합니다!

2019-10-19 09:12 UTC, hyojaekim commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ArgumentResolver.java
> +    public Object[] resolve(Method method) {
**클라이언트에서 유효한 요청**을 받은 다음
해당 메소드를 찾고 **메소드의 parameter를 가져오는 역할**을 하는데
피드백 내용을 토대로 **일치하지 않는 parameter에 대해서 예외**를 던지도록 수정했습니다.

그런데 **클라이언트에서 유효한 요청**을 보냈기 때문에 **4xx 클라이언트 요청에 대한 오류보다**는 
**서버 오류**가 맞겠다고 싶어서 500 에러로 처리하려고 합니다. 어떤 에러로 처리하는게 좋을까요??!

또 궁금한게 있는데 
`
private Object[] getParameters(HttpServletRequest request, HttpServletResponse response) {
        try {
            ArgumentResolver argumentResolver = new ArgumentResolver(request, response);
            return argumentResolver.resolve(method);
        } catch (NotMatchParameterException e) {
            response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            throw new NotMatchParameterException();
        }
    }
`

상태 코드를 설정할 때, 위와 같이 설정하면 될까요?!

2019-10-21 11:39 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ArgumentResolver.java
> +    public Object[] resolve(Method method) {
스프링에서 RequestParam 어노테이션을 사용할 때 500 서버에러를 상태코드로 받나요?
서버에러는 말 그대로 서버에서 예기치 못한 에러가 발생했을 때 나오는 것이죠!

http status code는 client 측에 우리가 약속된 http 상태 코드로 어떤 부분이 잘못되었다는 것인지 알려주기 위해서 사용하죠!

`@RequestParam("userId") String userId`
url?userI=abc 로 요청을 보냈을 경우 500에러를 반환해주어야 할까요?

2019-10-21 11:51 UTC, jeonghoon1107 approved these changes
안녕하세요 효오!
인자 매핑까지 깔끔하게 구현해주셨네요 💯 
관련하여 몇가지 간단한 피드백과 질문해주신 것에 대한 답변 남겼습니다!
미션 진행하느라 고생많으셨습니다 :)
추가적인 질문은 언제든 DM 주세요!

2019-10-21 11:51 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/argumentResolver/RequestResolverAdapter.java
> +        return parameterType.equals(HttpServletRequest.class);
isAssignableFrom를 사용해보면 어떨까요?
`HttpServletRequest.class.isAssignableFrom(parameterType)`
NPE가 발생할 수 있는 곳에는 항상 유의하면 좋을 것 같아요!

2019-10-21 11:51 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/argumentResolver/ArgumentResolver.java
> +public class ArgumentResolver {
객체를 argument로 받을 수 있도록 처리하면 좋았을텐데 아쉽네요!

2019-10-21 11:52 UTC, merged