[MVC - Step2] 이지 미션 제출합니다
woowacourse/jwp-mvc pull request #63
Opened 2019-10-10 10:19 UTC by skygl

안녕하세요! 이지입니다.
2단계의 요구사항을 구현하고 PR 보냅니다.
다음 PR에 추가 미션과 테스트 코드를 작성하겠습니다.
감사합니다~

2019-10-11 01:28 UTC, young891221 requested changes
수고하셨습니다. 이지!
2단계는 수월하게 진행해 주셨네요! 👍 
크게 개선할 부분은 많지 않아 몇 가지 포인트만 집었습니다. 확인 부탁드립니다.

2019-10-11 01:28 UTC, young891221 commented on nextstep-mvc/src/main/java/nextstep/utils/JsonUtils.java
> +        ObjectMapper objectMappper = new ObjectMapper();
매번 `new ObjectMapper()`를 생성하는 비용이 들거 같네요.

2019-10-11 01:28 UTC, young891221 commented on nextstep-mvc/src/main/java/nextstep/mvc/handleradapter/AnnotationHandlerAdapter.java
> +    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
여러군데에서 Object를 사용한 강제 캐스팅이 많네요. 이를 인터페이스로 두고 개선해 보면 어떨까요?
예를 들어, 현재는 `ModelAndView` 안에 `View`라는 필드가 존재하는데요. 이를 인터페이스화하여 여러 구현타입을 받을 수 있도록 하면 어떨까요?  `View`는 각각 명시적인 반환 타입을 구현한 클래스들이 존재하도록 만들 수 있을 것 같습니다.

2019-10-14 07:13 UTC, skygl commented on nextstep-mvc/src/main/java/nextstep/utils/JsonUtils.java
> +        ObjectMapper objectMappper = new ObjectMapper();
`    private static final ObjectMapper objectMapper = new ObjectMapper();
`
ObjectMapper를 static으로 만들어놓고, 재사용하도록 구현했습니다.

2019-10-14 07:59 UTC, skygl commented on nextstep-mvc/src/main/java/nextstep/mvc/handleradapter/AnnotationHandlerAdapter.java
> +    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
고민하다가 일단 ModelAndView에서 View를 Object로 들고있도록 구현했습니다. 그런데 컨트롤러에서 여러가지 리턴타입을 가진다면, 특히 java에서 지원하는 클래스들(예를들어 String) 리턴한다면 강제 캐스팅을 사용할 수밖에 없지 않을까요??

2019-10-14 12:15 UTC, young891221 approved these changes
안녕하세요 이지~! 피드백 반영 잘 해주셨네요 👍 
머지하겠습니다:)

2019-10-14 12:15 UTC, young891221 commented on nextstep-mvc/src/main/java/nextstep/mvc/handleradapter/AnnotationHandlerAdapter.java
> +    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
맞습니다. 그러한 부분은 제네릭으로 처리하고 정형화된 부분은 인터페이스로 추상화 시켜서 처리하는게 더 깔끔해서요ㅎㅎ
일단 지금 처리하신 방법도 문제없다고 생각되네요.

2019-10-14 12:15 UTC, merged