Yunheehyeon
woowacourse/jwp-mvc pull request #75
Opened 2019-10-11 14:26 UTC by yunheehyeon

2019-10-12 13:09 UTC, jeonghoon1107 requested changes
안녕하세요 유니!
몇가지 피드백남겼으니 확인부탁드려요 :)

2019-10-12 13:09 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/JsonView.java
> +        ObjectMapper objectMapper = new ObjectMapper();
objectMapper를 해당 메서드에서 매번 만드는 것은 불필요할 것 같아요!

2019-10-12 13:09 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerParameterMapper.java
> +public class ControllerParameterMapper {
클래스로 구현하셨네요 👍

2019-10-12 13:09 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerParameterMapper.java
> +        if (primitiveCast.containsKey(clazz)) {
interface를 사용하면 if문을 제거할 수 있을 것 같아요. (HandlerAdapter와 같이)

2019-10-13 13:18 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerParameterMapper.java
> +        if (primitiveCast.containsKey(clazz)) {
반영했습니다. 
User.class 와 메소드의 파라미터로 가져온 class 를 equals 로 비교하면 false 가 나오는 이유는 어디서 찾아 보면 좋을까요? 일단은 패키지로 비교를 했습니다.

2019-10-13 13:21 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/view/JsonView.java
> +        ObjectMapper objectMapper = new ObjectMapper();
JsonView는 매번 객체로 만들어서 사용하기 때문에  생성자에서 초기화 해주는 것보다 상수로 가지고 있도록 변경했습니다.

2019-10-14 11:25 UTC, jeonghoon1107 requested changes
안녕하세요 유니!
프레임워크와 애플리케이션에 대한 혼동이 있는 것 같아서 피드백남겼어요.
확인부탁드려요 :)

2019-10-14 11:25 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/UserParameterAdepter.java
> +        return clazz.getCanonicalName().equals(User.class.getCanonicalName());
User만 받을 수 있는 것 보다 더 확장성이 있으면 좋을 것 같아요.
해당하는 부분은 프레임워크인데, 애플리케이션의 User를 가지고 있는 것은 맞지 않아요!
현재 멀티모듈로 구성되어 있는데 의존성에 대해서 공부해보는 것이 좋을 것 같아요.

![image](https://user-images.githubusercontent.com/16200738/66742217-24c52500-eeb2-11e9-8892-7d31d61d3125.png)

2019-10-14 11:25 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/ParameterAdepter.java
> +public interface ParameterAdepter {
Adapter 오타인가요 :(

2019-10-14 12:43 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/ParameterAdepter.java
> +public interface ParameterAdepter {
수정했습니다. 😅

2019-10-14 12:44 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/UserParameterAdepter.java
> +        return clazz.getCanonicalName().equals(User.class.getCanonicalName());
애플리케이션에서 사용할 클래스를 추가할 수 있도록 만들어 봤습니다.

2019-10-18 10:09 UTC, yunheehyeon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/UserParameterAdepter.java
> +        return clazz.getCanonicalName().equals(User.class.getCanonicalName());
MethodParameter 를 적용해서 반영했습니다.

2019-10-20 07:50 UTC, jeonghoon1107 approved these changes
안녕하세요 유니!
쉽지 않았을텐데 인자 매핑까지 구현 잘 해주셨네요 💯 
미션 진행하느라 고생 많으셨습니다 :)

2019-10-20 07:50 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/MethodParameter.java
> +        return getParameterType().equals(clazz);
isAssignableFrom을 사용해도 좋을 것 같아요!

2019-10-20 07:50 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/adepter/IntegerParameterAdapter.java
> +public class IntegerParameterAdapter implements ParameterAdapter {
primitive type은 하나로 묶을 수 있을 것 같아요.
methodParameter.getParameterType().isPrimitive();

2019-10-20 07:50 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/controllermapper/ControllerParameterMapper.java
> +public class ControllerParameterMapper {
테스트가 없는 것이 아쉽네요 ㅠㅠ
각각 ParameterAdapter에 대한 테스트가 있으면 좋을 것 같아요.

2019-10-20 07:50 UTC, merged