[MVC - Step 2] 티버 미션 제출합니다.
woowacourse/jwp-mvc pull request #79
Opened 2019-10-12 12:58 UTC by yjll1019

감사합니다 :)

2019-10-13 12:02 UTC, byjo requested changes
2단계 미션 학습 테스트와 함께 잘 구현하셨어요 👍
간단한 피드백 드렸는데, 반영 후 미션 마무리 하면 될 것 같아요.
코멘트 확인 부탁드려요!

2019-10-13 12:02 UTC, byjo commented on slipp/src/main/java/slipp/controller/ProfileController.java
> +@Controller
어노테이션 기반 프레임워크를 만든 이유는 새로운 기능이 추가될 때마다 생기는 컨트롤러를 줄여 유지보수를 용이하게 하기 위해서였죠.
새로운 매핑 방법을 적용하면서 컨트롤러의 수를 줄여보면 어떨까요?

그리고 이렇게 기존에 서비스중인 코드를 변경할 때는 기존 코드 기반으로 통과하는 테스트를 만든 후, 전환 후 그 테스트가 잘 돌아가는지 확인하면 장애 없이 안전하게 변경이 가능하겠죠. :)

2019-10-13 12:02 UTC, byjo commented on slipp/src/main/java/slipp/controller/api/UserController.java
> +        User user = JsonUtils.toObject(requestBody, User.class);
참고로 ObjectMapper가 stream을 직접 이용할 수도 있어요.
```
   objectMapper.readValue(req.getReader(), User.class)
```
- [javadoc - ObjectMapper](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html#readValue(java.io.Reader,%20java.lang.Class))

2019-10-13 12:02 UTC, byjo commented on nextstep-mvc/src/test/java/nextstep/mvc/tobe/JacksonLearningTest.java
> +public class JacksonLearningTest {
학습 테스트 👍

2019-10-13 12:02 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/exception/NotFoundModelException.java
> +        super("model");
다른 custom exception 들 처럼 에러 메시지가 명료하면 더 좋을 것 같아요.

2019-10-14 04:18 UTC, yjll1019 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/exception/NotFoundModelException.java
> +        super("model");
수정했습니다! 좀 더 자세히 확인하지 못한 점 죄송합니다.

2019-10-14 05:45 UTC, yjll1019 commented on slipp/src/main/java/slipp/controller/api/UserController.java
> +        User user = JsonUtils.toObject(requestBody, User.class);
수정했습니다! 코드 라인이 줄어 읽기 편해졌네요. 감사합니다 :)

2019-10-15 13:45 UTC, yjll1019 commented on slipp/src/main/java/slipp/controller/ProfileController.java
> +@Controller
네!  UserController를 생성하여 User관련 기능을 하는 메서드들을 두었습니다!
테스트 코드도 추가하였습니다! 감사합니다. :)

2019-10-16 12:04 UTC, byjo approved these changes
피드백 반영해주신 사항 확인했습니다.
테스트와 함께 리팩토링 잘 진행하셨어요. 👏
미션 마무리 할게요. 약 2주동안 즐거운 시간이였습니다! 😊

2019-10-16 12:04 UTC, byjo commented on slipp/src/main/java/slipp/controller/api/UserController.java
> +        User user = objectMapper.readValue(req.getReader(), User.class);
JsonUtils에 readValue 메소드를 추가하고 컨트롤러는 유틸 메소드를 사용해도 좋을 것 같아요. :)

2019-10-16 12:05 UTC, merged