[MVC - Step 2] 로비 미션 제출합니다.
woowacourse/jwp-mvc pull request #80
Opened 2019-10-13 09:50 UTC by kangmin46

레거시 코드를 지우고 새로운 어노테이션 기반 컨트롤러로 동작하게끔 만들었습니다.

ViewResolver를 사용해서 view를 선택해주는 로직을 짜보았습니다.

많은 피드백 부탁드립니다~

2019-10-14 11:53 UTC, jihan805 requested changes
안녕하세요 ~! 2단계 구현도 잘하셨네요 👍 
몇가지 피드백 남겼으니 확인 후 머지할게요 :)

2019-10-14 11:53 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ModelAndView.java
>      public ModelAndView() {
디폴트 생성자를 통해 JsonView를 설정하는것도 좋지만, 아래 
```
public ModelAndView(View view) {
        this.view = view;
    }
```
를 사용해도 충분할것 같아요!

2019-10-14 11:53 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerScanner.java
> +public class ControllerScanner {
ControllerScanner  클래스 분리 👍 
해당 클래스는 url, method mapping 등을 모두 처리 하는 것 보단, Controller 어노테이션이 붙은 클래스를 찾는 역할만으로도 충분할 것 같아요 :)

2019-10-14 11:53 UTC, jihan805 commented on slipp/src/main/java/slipp/tobe/controller/ForwardController.java
>      public String index(HttpServletRequest req, HttpServletResponse res) {
현재 구현한 코드를 바탕으로 String이 아닌 ModelAndView를 리턴하거나, String 을 리턴할 수 있도록 해야하지 않을까요?

2019-10-14 11:53 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/JsonView.java
> +            objectMapper.writeValue(response.getWriter(), model.values().toArray()[0]);
objectMapper의  writeValue를 이용하여 구현했네요 👍

2019-10-14 11:53 UTC, jihan805 commented on slipp/src/main/java/slipp/tobe/controller/RestUserController.java
> +        response.setStatus(201);
status 값을 사용하고자 한다면 상수로 관리하는 것도 깔끔한 방법일 것 같아요 :)

2019-10-14 11:53 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        HandlerAdapter handlerAdapter = findHandlerAdapter(handler);
요구사항2에 맞게 as is의 mvc 프레임워크 관련 코드를 제거해보아도 좋을 것 같아요 :)

2019-10-18 08:41 UTC, kangmin46 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerScanner.java
> +public class ControllerScanner {
저도 조금 마음에 걸렸었는데 역시 지적해주셨네요 ㅎㅎ
ControllerScanner와 RequestMappingScanner로 분리했는데 그 두 부분의 로직이 조금 짧은거 같아 마음에 좀 걸리긴 하네요!
혹시 더 좋은 방향이 있으면 조언해 주시면 감사하겠습니다~

2019-10-20 04:11 UTC, jihan805 approved these changes
안녕하세요 ~! 피드백 반영 잘하셨습니다 💯 
답변 남겨두었으니 확인해주세요!
머지 할게요 미션 구현하느라 고생 많으셨어요 :)

2019-10-20 04:11 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/ControllerScanner.java
> +public class ControllerScanner {
로직의 길이 보다는 역할에 맞게 분리하는 것이 더 좋은 방향일 것 같습니다 :)

2019-10-20 04:12 UTC, merged